import { useState } from "react";
import { Download, FileText, Search } from "lucide-react";

const API_URL = "http://localhost:5000";

export default function Admin() {
  const [password, setPassword] = useState(""); const [registrations, setRegistrations] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [query, setQuery] = useState(""); const [ageGroup, setAgeGroup] = useState("All"); const [adminToken, setAdminToken] = useState("");
  const load = async (e) => { e.preventDefault(); setLoading(true); setError(""); try { const login = await fetch(`${API_URL}/api/registration/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const auth = await login.json(); if (!login.ok || !auth.success) throw new Error(auth.message || "Unable to sign in."); setAdminToken(auth.token); const response = await fetch(`${API_URL}/api/registration/admin`, { headers: { Authorization: `Bearer ${auth.token}` } }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Unable to load registrations."); setRegistrations(result.registrations); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const openDocument = async (type, filePath) => { try { const name = filePath?.split("/").filter(Boolean).pop(); if (!name) throw new Error("Document is unavailable."); const response = await fetch(`${API_URL}/api/registration/admin/document/${type}/${encodeURIComponent(name)}`, { headers: { Authorization: `Bearer ${adminToken}` } }); if (!response.ok) throw new Error("Unable to open document."); const url = URL.createObjectURL(await response.blob()); window.open(url, "_blank", "noopener,noreferrer"); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (err) { setError(err.message); } };
  const ages = ["All", ...new Set(registrations.map((x) => x.ageGroup).filter(Boolean))]; const visible = registrations.filter((x) => `${x.fullName} ${x.registrationId} ${x.mobile}`.toLowerCase().includes(query.toLowerCase()) && (ageGroup === "All" || x.ageGroup === ageGroup));
  const exportCsv = () => { const csv = [["Registration ID", "Name", "Payment Status", "Amount"], ...visible.map((x) => [x.registrationId, x.fullName, x.paymentStatus || "Pending", x.amountPaid || 0])].map((r) => r.join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "registrations.csv"; a.click(); URL.revokeObjectURL(url); };
  return <main className="admin-page"><section className="admin-header"><p className="hero-badge">ADMINISTRATION</p><h1>Registered Students</h1><p>Securely view registrations, documents, and payment status.</p></section><form className="admin-login" onSubmit={load}><label htmlFor="admin-password">Admin password</label><div><input id="admin-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /><button className="button-primary" disabled={loading}>{loading ? "Loading..." : "View registrations"}</button></div>{error && <p className="error-text">{error}</p>}</form>{registrations.length > 0 && <section className="admin-table-wrap"><div className="admin-table-title"><div><h2>Students</h2><span>{visible.length} of {registrations.length} registrations</span></div><button className="csv-button" onClick={exportCsv}><Download size={17} /> Download CSV</button></div><div className="admin-filters"><label className="search-field"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, ID or mobile" /></label><select value={ageGroup} onChange={(e) => setAgeGroup(e.target.value)}>{ages.map((x) => <option key={x}>{x}</option>)}</select></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>ID</th><th>Student</th><th>Mobile</th><th>Documents</th><th>Payment</th></tr></thead><tbody>{visible.map((s) => { const docs = [["documents", s.aadhaarCard, "Aadhaar"], ["documents", s.dobCertificate, "DOB certificate"], ["rsfi", s.rsfiCard, "RSFI"]].filter(([, x]) => x); const payment = s.paymentStatus || "Pending"; return <tr key={s._id}><td>{s.registrationId}</td><td>{s.fullName}<small className="admin-subtext">{s.category} · {s.races?.join(", ")}</small></td><td>{s.mobile}</td><td><div className="document-links">{docs.length ? docs.map(([type, file, label]) => <button key={label} onClick={() => openDocument(type, file)}><FileText size={14} /> {label}</button>) : "—"}</div></td><td><span className={`payment-status ${payment.toLowerCase()}`}>{payment}</span><small className="admin-subtext">₹{s.amountPaid || 0}</small></td></tr>; })}</tbody></table></div></section>}</main>;
}
