import { useState } from "react";
import { validateForm } from "../utils/validateForm";
import Footer from "../components/Footer";
import RegistrationHeader from "../components/RegistrationHeader";
import RegistrationHero from "../components/RegistrationHero";
import ParticipantForm from "../components/ParticipantForm";
import DocumentsUpload from "../components/DocumentsUpload";
import PaymentSummary from "../components/PaymentSummary";
const start = {rsfiRegistrationNo:"",fullName:"",dob:"",ageGroup:"",gender:"",category:"",races:[],club:"",coachName:"",mobile:"",state:""};
export default function Registration(){const [formData,setFormData]=useState(start),[documents,setDocuments]=useState({}),[errors,setErrors]=useState({}),[agreed,setAgreed]=useState(false),[loading,setLoading]=useState(false);const handleChange=e=>{const {name,value,checked}=e.target;setFormData(d=>name==="category"?{...d,category:value,races:[]}:name==="races"?{...d,races:["Quad","Inline"].includes(d.category)?checked?[...d.races,value]:d.races.filter(x=>x!==value):[value]}:{...d,[name]:name==="mobile"?value.replace(/\D/g,""):value});setErrors(x=>({...x,[name]:""}));};const register=async()=>{const issues=validateForm(formData,documents,agreed);if(Object.keys(issues).length)return setErrors(issues);setLoading(true);try{const r=await fetch("http://localhost:5000/api/payment/create-order",{method:"POST"}),j=await r.json();if(!j.success)throw new Error(j.message);new window.Razorpay({key:import.meta.env.VITE_RAZORPAY_KEY_ID,amount:j.order.amount,currency:j.order.currency,name:"1st Agra Regional Skating Championship",order_id:j.order.id,prefill:{name:formData.fullName,contact:formData.mobile},handler:async p=>{const v=await fetch("http://localhost:5000/api/payment/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...p,registrationData:{...formData,...documents}})}),result=await v.json();if(!result.success)throw new Error(result.message);alert(`Registration submitted successfully for the 1st Agra Regional Skating Championship.\n\nReceipt No: ${result.registration.registrationId}\nPayment ID: ${result.registration.paymentId}`);}}).open();}catch(e){alert(e.message||"Unable to start payment.");}finally{setLoading(false);}};return <><RegistrationHeader/><main className="registration-page"><RegistrationHero/><div className="form-progress"><span>1. Details</span><span>2. Race</span><span>3. Documents</span><span>4. Payment</span></div><ParticipantForm formData={formData} handleChange={handleChange} errors={errors}/><DocumentsUpload documents={documents} setDocuments={setDocuments} errors={errors} setErrors={setErrors}/><PaymentSummary handleRegistration={register} agreed={agreed} setAgreed={setAgreed} errors={errors} setErrors={setErrors} loading={loading}/></main><Footer/></>;}
